def load_data():
    #Generation 1
    gen1 = ["José Arcadio Buendía", "Úrsula Iguarán"]
    + married(gen1[0], gen1[1])
    + cousin(gen1[0], gen1[1])
    + buendia_blood(gen1[0], True)
    + buendia_blood(gen1[1], True)
    + gender(gen1[0], 'Male')
    + gender(gen1[1], 'Female')

    # Generation 2
    gen2 = ["Colonel Aureliano Buendía", "José Arcadio Buendía (II)", "Amaranta Buendía", "Pilar Ternera", "Remedios Moscote", "Rebeca Buendía"]
    + parent(gen1[0], gen2[0])
    + parent(gen1[1], gen2[0])
    + parent(gen1[0], gen2[1])
    + parent(gen1[1], gen2[1])
    + parent(gen1[0], gen2[2])
    + parent(gen1[1], gen2[2])
    + gender(gen2[2], 'Female')
    + gender(gen2[0], 'Male')
    + gender(gen2[1], 'Male')
    + gender(gen2[3], 'Female')
    + gender(gen2[4], 'Female')
    + gender(gen2[5], 'Female')
    + buendia_blood(gen2[0], True)
    + buendia_blood(gen2[1], True)
    + buendia_blood(gen2[2], True)
    + buendia_blood(gen2[3], False)
    + buendia_blood(gen2[4], False)
    + buendia_blood(gen2[5], False)
    + buendia(gen2[0], True)
    + buendia(gen2[1], True)
    + buendia(gen2[2], True)
    + buendia(gen2[3], False)
    + buendia(gen2[4], True)
    + buendia(gen2[5], True)
    + married(gen2[0], gen2[4])
    + married(gen2[1], gen2[5])


    # Generation 3
    gen3 = ["The 17 Aurelianos", "Aureliano José Buendía", "Arcadio (José Arcadio III)", "Santa Sofía de la Piedad"]
    + parent(gen2[0], gen3[0])
    + parent(gen2[0], gen3[1])
    + parent(gen2[3], gen3[1])
    + parent(gen2[1], gen3[2])
    + parent(gen2[3], gen3[2])
    + gender(gen3[0], 'Male')
    + gender(gen3[1], 'Male')
    + gender(gen3[2], 'Male')
    + gender(gen3[3], 'Female')
    + buendia_blood(gen3[0], True)
    + buendia_blood(gen3[1], True)
    + buendia_blood(gen3[2], True)
    + buendia_blood(gen3[3], False)
    + buendia(gen3[0], True)
    + buendia(gen3[1], True)
    + buendia(gen3[2], True)
    + buendia(gen3[3], True)
    + married(gen3[2], gen3[3])

    # Generation 4
    gen4 = ["Remedios the Beauty", "Fernanda del Carpio", "Aureliano Segundo Buendía", "José Arcadio Segundo Buendía"]
    + parent(gen3[2], gen4[0])
    + parent(gen3[3], gen4[0])
    + parent(gen3[2], gen4[2])
    + parent(gen3[3], gen4[2])
    + parent(gen3[2], gen4[3])
    + parent(gen3[3], gen4[3])
    + gender(gen4[0], 'Female')
    + gender(gen4[1], 'Female')
    + gender(gen4[2], 'Male')
    + gender(gen4[3], 'Male')
    + buendia_blood(gen4[0], True)
    + buendia_blood(gen4[1], False)
    + buendia_blood(gen4[2], True)
    + buendia_blood(gen4[3], True)
    + buendia(gen4[0], True)
    + buendia(gen4[1], True)
    + buendia(gen4[2], True)
    + buendia(gen4[3], True)
    + married(gen4[2], gen4[1])

    gen5 = ['José Arcadio Buendía (IV)', 'Renata Remedios Buendía (Meme)', 'Mauricio Babilonia', 'Amaranta Úrsula Buendía']
    + parent(gen4[2], gen5[0])
    + parent(gen4[1], gen5[0])
    + parent(gen4[2], gen5[1])
    + parent(gen4[1], gen5[1])
    + parent(gen4[2], gen5[3])
    + parent(gen4[1], gen5[3])
    + gender(gen5[0], 'Male')
    + gender(gen5[1], 'Female')
    + gender(gen5[2], 'Male')
    + gender(gen5[3], 'Female')
    + buendia_blood(gen5[0], True)
    + buendia_blood(gen5[1], True)
    + buendia_blood(gen5[2], False)
    + buendia_blood(gen5[3], True)
    + buendia(gen5[0], True)
    + buendia(gen5[1], True)
    + buendia(gen5[2], False)
    + buendia(gen5[3], True)

    gen6 = ['Aureliano (II)', 'Gaston']
    + parent(gen5[1], gen6[0])
    + parent(gen5[2], gen6[0])
    + gender(gen6[0], 'Male')
    + gender(gen6[1], 'Male')
    + buendia_blood(gen6[0], True)
    + buendia_blood(gen6[1], False)
    + buendia(gen6[0], True)
    + buendia(gen6[1], False)
    + married(gen6[1], gen5[3])

    gen7 = ['Aureliano (III)']
    + parent(gen6[0], gen7[0])
    + parent(gen5[3], gen7[0])
    + buendia_blood(gen7[0], True)
    + buendia(gen7[0], True)

    return [gen1, gen2, gen3, gen4, gen5, gen6, gen7]